version: '3.8'

services:
  grain-relay:
    build: .
    container_name: grain-relay
    ports:
      - "8181:8181"
    environment:
      # Relay Basic Information
      RELAY_NAME: "🌾 Mon Relay GRAIN"
      RELAY_DESCRIPTION: "Un relay Nostr communautaire français"
      RELAY_BANNER: "https://example.com/banner.jpg"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_PUBKEY: "your_relay_pubkey_here"
      RELAY_CONTACT: "mailto:admin@monrelay.fr"
      
      # Software information is automatically set and cannot be overridden
      
      # Policies
      RELAY_PRIVACY_POLICY: "https://monrelay.fr/privacy"
      RELAY_TERMS_OF_SERVICE: "https://monrelay.fr/terms"
      RELAY_POSTING_POLICY: "https://monrelay.fr/posting-policy"
      
      # Geographic and Language Settings
      RELAY_COUNTRIES: "FR,BE,CH"  # France, Belgium, Switzerland
      RELAY_LANGUAGE_TAGS: "fr,fr-FR,en"
      RELAY_TAGS: "francophone,communautaire,open-access"
      
      # Limitations
      RELAY_MAX_MESSAGE_LENGTH: "524288"
      RELAY_MAX_CONTENT_LENGTH: "8196"
      RELAY_MAX_SUBSCRIPTIONS: "20"
      RELAY_MAX_LIMIT: "1000"
      RELAY_AUTH_REQUIRED: "false"
      RELAY_PAYMENT_REQUIRED: "false"
      RELAY_RESTRICTED_WRITES: "false"
      RELAY_CREATED_AT_LOWER_LIMIT: "1577836800"  # 2020-01-01
      RELAY_CREATED_AT_UPPER_LIMIT: "null"
    
    volumes:
      - grain_data:/app/data
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8181/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB service (if needed)
  mongo:
    image: mongo:7.0
    container_name: grain-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: grain
      MONGO_INITDB_ROOT_PASSWORD: grain_password

volumes:
  grain_data:
  mongo_data:

networks:
  default:
    name: grain-network